fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"
#index:
#    path: /
#    controller: App\Controller\DefaultController::index

captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
